### ISSUE TITLE
Add project to Graylog Marketplace

### ISSUE THREAD

**Issue by joschi** [nskazki/winston-tcp-graylog#1]
In order to make it easier for users to discover this project, it would be great if it was added to the [Graylog Marketplace](https://marketplace.graylog.org/).

Adding the project should be quite simple by using the GitHub integration of the Graylog Marketplace (http://docs.graylog.org/en/latest/pages/marketplace.html).

**Comment by nskazki** [comment]
great idea, thank - https://marketplace.graylog.org/addons/e6a77522-feb1-46cf-938a-9716e6b7f482

**Comment by joschi** [comment]
Thanks!
