### ISSUE TITLE
upgrade to gelf-pro 1.0.0

### ISSUE THREAD

**Issue by bangert** [nskazki/winston-tcp-graylog#3]
Thanks

**Comment by nskazki** [comment]
@bangert Hello. Sorry for incredible long waiting. Looks like I just missed your request.

ATM I don't have any graylog instance or free time to setup playground on my PC. 
So sorry, but I can't resolve your issue. Also, I leave the request open if someone wants to contribute.

**Comment by nskazki** [comment]
All the vulnerable packages including `gelf-pro` have been upgraded in `winston-tcp-graylog@1.0.14`.
`winston-tcp-graylog@1.0.13` has been deprecated.

```
$ yarn audit
yarn audit v1.19.1
0 vulnerabilities found - Packages audited: 3908
```

```
$ yarn outdated
yarn outdated v1.19.1
Package Current Wanted Latest Package Type    URL                                             
pkginfo 0.3.1   0.3.1  0.4.1  dependencies    https://github.com/indexzero/node-pkginfo#readme
winston 2.4.4   2.4.4  3.2.1  devDependencies https://github.com/winstonjs/winston#readme     
```
