### ISSUE TITLE
There's a security breach 

### ISSUE THREAD

**Issue by dtiziani** [nskazki/winston-tcp-graylog#8]
https://nodesecurity.io/advisories/577

its using gelf-pro version that uses a  lodash version with a breach.

**Comment by dtiziani** [comment]
If I make a pull request will you merge it?
basically it will only upgrade the lodash dependency to avoid the security issue, @nskazki

**Comment by nskazki** [comment]
Oh, I have no idea how did I miss your issue. Sure I'll merge your PR if you make it. 
Sorry for long waiting @dtiziani!

**Comment by nskazki** [comment]
This issue has been resolved some time ago.

**Comment by nskazki** [comment]
Actually it wasn't! Oh, I wish I paid more attention to my repositories...

**Comment by nskazki** [comment]
I'm sorry for not paying any attention to this repository for a long time.
All the vulnerable packages including `gelf-pro` have been upgraded in `winston-tcp-graylog@1.0.14`.
`winston-tcp-graylog@1.0.13` has been deprecated.

```
$ yarn audit
yarn audit v1.19.1
0 vulnerabilities found - Packages audited: 3908
```

```
$ yarn outdated
yarn outdated v1.19.1
Package Current Wanted Latest Package Type    URL                                             
pkginfo 0.3.1   0.3.1  0.4.1  dependencies    https://github.com/indexzero/node-pkginfo#readme
winston 2.4.4   2.4.4  3.2.1  devDependencies https://github.com/winstonjs/winston#readme     
```
